# Generated by Django 4.0.3 on 2022-03-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_peroid_start', models.DateTimeField()),
                ('time_peroid_end', models.DateTimeField()),
                ('price_open', models.DecimalField(decimal_places=2, max_digits=255)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=255)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=255)),
                ('price_close', models.DecimalField(decimal_places=2, max_digits=255)),
                ('volume_traded', models.DecimalField(decimal_places=5, max_digits=255)),
                ('trades_count', models.IntegerField()),
            ],
        ),
    ]
